
      !(function(){
        var uniAppViewReadyCallback = function(){
          setCssToHead([".",[1],"header-box{height:",[0,420],";width:",[0,750],";display:-webkit-box;display:-webkit-flex;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;flex-direction:column;background-image:-webkit-linear-gradient(left,#e75551,#c43164);background-image:linear-gradient(90deg,#e75551,#c43164);box-shadow:0 ",[0,4]," ",[0,8]," 0 #e6e6e6}\n.",[1],"diff-header{height:",[0,128],";width:100%;padding-top:",[0,40],";padding-top:",[0,20],"}\n.",[1],"banner,.",[1],"diff-header{display:-webkit-box;display:-webkit-flex;display:flex;box-sizing:border-box;-webkit-box-align:center;-webkit-align-items:center;align-items:center}\n.",[1],"banner{height:",[0,292],";width:",[0,750],";-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;flex-direction:column;color:#fff}\n.",[1],"banner wx-image{width:",[0,120],";height:",[0,120],";border-radius:50%;margin:",[0,30]," 0}\n.",[1],"user-info{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-box-align:center;-webkit-align-items:center;align-items:center;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"banner-desc{margin-top:",[0,10],";font-size:",[0,28],"}\n.",[1],"loginbtn{width:",[0,228],";height:",[0,68],";background-color:#fff;border-radius:",[0,44],";text-align:center;line-height:",[0,68],";font-size:",[0,32],";color:#e45252}\n.",[1],"list{min-height:",[0,110],";-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"item,.",[1],"list{width:",[0,750],";display:-webkit-box;display:-webkit-flex;display:flex}\n.",[1],"item{height:",[0,110],";border-bottom:",[0,2]," solid #e6e6e6;background-color:#fff;-webkit-box-align:center;-webkit-align-items:center;align-items:center;font-size:",[0,32],";color:#6c6c6c}\n.",[1],"item-name{-webkit-box-flex:1;-webkit-flex:1;flex:1}\n",],undefined,{path:"./pages/manage/manage.wxss"})();
document.dispatchEvent(new CustomEvent("generateFuncReady", { detail: { generateFunc: $gwx('./pages/manage/manage.wxml') } }));
        }
        if(window.__uniAppViewReady__){
          uniAppViewReadyCallback()
        }else{
          document.addEventListener('uniAppViewReady',uniAppViewReadyCallback)
        }
      })();
      