
      !(function(){
        var uniAppViewReadyCallback = function(){
          setCssToHead([".",[1],"tab-title{width:",[0,750],";display:-webkit-box;display:-webkit-flex;display:flex;margin:",[0,20]," 0}\n.",[1],"tab-title,.",[1],"tab-title .",[1],"tab{height:",[0,70],";-webkit-box-pack:center;-webkit-justify-content:center;justify-content:center}\n.",[1],"tab-title .",[1],"tab{width:",[0,280],";display:-webkit-inline-box;display:-webkit-inline-flex;display:inline-flex;-webkit-box-align:center;-webkit-align-items:center;align-items:center;border:",[0,2]," solid #e45252;box-sizing:border-box;color:#666}\n.",[1],"tab-title .",[1],"select{background-color:#d0021b;color:#fff}\n.",[1],"tab-title .",[1],"tab:first-child{border-radius:",[0,12]," 0 0 ",[0,12],"}\n.",[1],"tab-title .",[1],"tab:nth-child(2){border-radius:0 ",[0,12]," ",[0,12]," 0}\n.",[1],"week-box{width:",[0,750],";margin-top:",[0,60],"}\n.",[1],"week-box,.",[1],"week-left{display:-webkit-box;display:-webkit-flex;display:flex;min-height:",[0,730],"}\n.",[1],"week-left{width:",[0,130],";-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"week-left-item{width:",[0,130],";height:",[0,70],";line-height:",[0,70],";text-align:center;background-color:#c12158;border-radius:0 ",[0,35]," ",[0,35]," 0;margin-bottom:",[0,40],";color:#fff}\n.",[1],"week-left .",[1],"select{background-color:#e45252}\n.",[1],"week-right{-webkit-box-flex:1;-webkit-flex:1;flex:1;min-height:",[0,730],";-webkit-flex-wrap:wrap;flex-wrap:wrap;padding:0 ",[0,20]," 0 ",[0,30],";box-sizing:border-box}\n.",[1],"week-right,.",[1],"week-right-time{display:-webkit-box;display:-webkit-flex;display:flex}\n.",[1],"week-right-time{width:",[0,180],";height:",[0,134],";background-color:#fff;box-shadow:0 0 ",[0,8]," 0 #e6e6e6;border-radius:",[0,12],";margin:0 ",[0,10]," ",[0,10]," 0;font-size:",[0,28],";color:#666;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;flex-direction:column;overflow:hidden}\n.",[1],"week-right-time-top{width:",[0,180],";height:",[0,44],";line-height:",[0,44],";text-align:center;font-size:",[0,24],";background-color:#fff}\n.",[1],"week-right-time-bottom{-webkit-box-flex:1;-webkit-flex:1;flex:1;display:-webkit-box;display:-webkit-flex;display:flex;-webkit-box-align:center;-webkit-align-items:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;justify-content:center;width:",[0,180],";background-color:#d0021b;font-size:",[0,26],";color:#fff}\n.",[1],"week-right-item{width:",[0,180],";height:",[0,134],";background-color:#fff;box-shadow:0 0 ",[0,8]," 0 #e6e6e6;border-radius:",[0,12],";margin:0 ",[0,10]," ",[0,10]," 0;font-size:",[0,28],";color:#666;line-height:",[0,134],";text-align:center}\n",],undefined,{path:"./pages/basics/gangshao.wxss"})();
document.dispatchEvent(new CustomEvent("generateFuncReady", { detail: { generateFunc: $gwx('./pages/basics/gangshao.wxml') } }));
        }
        if(window.__uniAppViewReady__){
          uniAppViewReadyCallback()
        }else{
          document.addEventListener('uniAppViewReady',uniAppViewReadyCallback)
        }
      })();
      